---
title: "Capstone Prelim Data Exploration Summary"
author: "James Topor"
date: "September 27, 2017"
output:
  html_document: default
  pdf_document: default
---

NOTE: The full analysis used to generate this summary can be found here:

- https://github.com/jtopor/DDO-TNZ/blob/master/tanz-dataexp.Rmd

# Complete Cases

On an initial read of the data we find the following:

- 53281 complete cases

- 6119 rows with NA's

- 10.3% of rows have NA's

However, many of the categorical variables are comprised of character strings that are simply blank. Such strings should logically be considered as missing (or "NA"). As such, after converting the blank strings to "NA" values we find the following:

- Only 27813 complete cases

- 31587 rows with NA's

- 53.17% of rows have NA's


# Summary of Variables in Data Set

### Numeric Variables

| Numeric Variables | Comments                            |
|-------------------|-------------------------------------|
| amount_tsh        | 41,639 of 59,400 records = "0"      |
| gps_height        | 20,438 of 59,400 records = "0"      |
| population        | 21,381 of 59.400 records = "0"      |
| longitude         | 1,812 zero values: likely invalid   |
| latitude          | 1,819 values < -1: likely invalid   |
| num_private       | 58,643 of 59.400 records = "0"      |


### Categorical variables

Please note that the NA totals listed below were calculated *after* converting blank character strings to __NA__ values

| Categorical Variable | Distinct Values | NA's | Comments                      |
|----------------------|-----------------|------|-------------------------------|
| funder               | 1898            | 3635 |                               |
| installer            | 2146            | 3655 |                               |
| wpt_name             | 37400           | 0    |                               |
| basin                | 9               | 0    |                               |
| subvillage           | 19288           | 371  |                               |
| region               | 21              | 0    |                               |
| region_code          | 27              | 0    |                               |
| district_code        | 20              | 0    |                               |
| lga                  | 125             | 0    |                               |
| ward                 | 2092            | 0    |                               |
| public_meeting       | 3               | 3334 | binary + NA's                 |
| scheme_management    | 13              | 3877 |                               |
| scheme_name          | 2697            | 28166|                               |
| permit               | 3               | 3056 | binary + NA's                 |
| construction_year    | 55              | 20709|                               |
| extraction_type      | 18              | 0    |                               |
| extraction_type_group| 13              | 0    | composite of extr_type        |
| extraction_type_class| 7               | 0    | composite of extr_type_class  |
| management           | 12              | 0    |                               |
| management_group     | 5               | 0    |                               |
| payment              | 7               | 0    |                               |
| payment_type         | 7               | 0    | dupe of payment               |
| water_quality        | 8               | 0    |                               |
| quality_group        | 6               | 0    | composite of water_quality    |
| quantity             | 5               | 0    |                               |
| quantity_group       | 5               | 0    | dupe of quantity              |
| source               | 10              | 0    |                               |
| source_type          | 7               | 0    | composite of source           |
| source_class         | 3               | 0    | binary + "unknow              |
| waterpoint_type      | 7               | 0    |                               |
| waterpoint_type_group| 6               | 0    | composite of waterpoint_type  |


Four __region__ names are found to have no non-zero values for the following variables:

- amount_tsh
- gps_height
- construction_year
- num_private
- population

The four regions are:

- Dodoma 
- Kagera 
- Mbeya
- Tabora

These 4 regions comprise __12,115__ of the __59,400__ records in the data set __(20.39%)__, including __27__ of the unique __lga__'s, __514__ of the unique __wards__ and __4644__ of the unique __subvillages__.  

The __12,115__ records covered by these regions represent approximately __60%__ of the zero values found within the __gps_height__ (12,115 / 20,438), __population__ (12,115 / 21,381), and __construction_year__ (12,115 / 20,709) variables.

The lack of non-zero values throughout the four indicated regions for the five variables listed above makes it highly unlikely that we will be able to effectively derive imputed values for the zero values of those five variables using the geographical indicators provided within the data set.


### Administrative / Non-Predictive Variables

| Administrative Variables | Data Type |
|--------------------------|-----------|
| id                       | int       |
| date_recorded            | date      |
| recorded_by              | char str  |


The administrative variables shown above have no predictive value and will be ignored for purposes of model building. The __id__ variable serves as a unique identifier for each data record within the data set. The __date_recorded__ variable indicates the date on which the each record presented within the data was collected, while the __recorded_by__ variable contains the name of the survey firm that collected the data.
